version: "3.8"

services:
  postgres_database:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8887:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pg-admin-data:/var/lib/pgadmin
  proxy:
    build:
      context: .
      dockerfile: ./Proxy/Dockerfile
    ports:
      - 5000:80
  app1:
    build:
      context: .
      dockerfile: ./LoggingAPI/Dockerfile
    depends_on:
      - postgres_database
    ports:
      - 5001:80

  app2:
    build:
      context: .
      dockerfile: ./LoggingAPI/Dockerfile
    depends_on:
      - postgres_database
    ports:
      - 5002:80
  app3:
    build:
      context: .
      dockerfile: ./LoggingAPI/Dockerfile
    depends_on:
      - postgres_database
    ports:
      - 5003:80

  app4:
    build:
      context: .
      dockerfile: ./LoggingAPI/Dockerfile
    depends_on:
      - postgres_database
    ports:
      - 5004:80
  app5:
    build:
      context: .
      dockerfile: ./LoggingAPI/Dockerfile
    depends_on:
      - postgres_database
    ports:
      - 5005:80
volumes:
  pg-db-data:
  pg-admin-data:
